apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-access-monitor.fullname" . }}-config
  labels:
    {{- include "k8s-access-monitor.labels" . | nindent 4 }}
data:
  input.json: |
{{ .Values.mainApp.inputConfig | indent 4 }}
